name: Run lab-student-survey

on:
  schedule:
    # every week
    - cron: "0 0 * * 0"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf
      - name: Install and run lab-student-survey
        run: pipx run lab-student-survey && pipx run lab-student-survey -p ECCS,CC0 && pipx run lab-student-survey -p CC0
        env:
          LAB_STUDENT_SURVEY_FILE_URL: ${{ secrets.LAB_STUDENT_SURVEY_FILE_URL }}
          LAB_STUDENT_SURVEY_FOLDER_URL: ${{ secrets.LAB_STUDENT_SURVEY_FOLDER_URL }}
          GDRIVE_SERVICE_SECRETS: ${{ secrets.GDRIVE_SERVICE_SECRETS }}
